### ISSUE TITLE
Reproducibility of a notebook environment

### ISSUE THREAD

**Issue by JohnScience** [conda-forge/notebook-feedstock#103]
### Comment:

Hi. I'm trying to make a reproducible environment for browsing `.ipynb` Jupyter Notebook so that I can eventually make a Binder repo and `conda` seems to be a way to do that. 

I've found that by default `empheq` extension is disabled in MathJax. I can enable it by altering one of my dependencies, which happens to be your package -- `notebook`.

If I understand correctly, what I need to do is to create a patched package and offer it on a personal channel. Is this correct?

P.S. I'm a Rust developer so I'm only remotely familiar with Python ecosystem.

**Comment by bollwyvl** [comment]
> a way to do that.

If you only need it for the relatively cool, but still pretty little R of "runs on binder in a single repo", a [postBuild](https://repo2docker.readthedocs.io/en/latest/config_files.html#postbuild-run-code-after-installing-the-environment) file in the repo in question is probably the lightest touch, as it will happen at build time and get cached.

If you need it for mulitple repos, figuring out a way to do it with [an extension](https://jupyter-notebook.readthedocs.io/en/stable/extending/index.html) is the cleanest approach. This would typically involve creating a public repo of a pip package, which your binder could reference by URL. To make it big "R" reproducible, one could then optionally publish it on PyPI, and (optionally) create a new conda-forge package.

> patched package and offer it on a personal channel.

This _would_ work, but you'd want to make sure you had a plan for e.g. keeping up with upstream versions to avoid shipping known-insecure software.

You could:
- install `conda-build` (probably start with a [miniforge](https://github.com/conda-forge/miniforge/))
- clone `notebook-feedstock`
  - in `meta.yaml`
    - apply some [`#/source/patches`](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#patches) to the upstream notebook source 
    - make a "distinctive" [`#build/string`](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#build-number-and-string) like `string: john_science`
- build the conda package
- upload the conda package to anaconda.org
  - or generate your own channel with `conda index` and upload to really any public web server
- in your binder repo's `environment.yml`
  - reference that channel in `#/channels` as a higher-priority than `conda-forge`
  - add your custom build string, e.g. `- notebook=*john_science`

At any rate, there's nothing much we can do directly on this repo to help you, so i'll close this out! You may wish to ask around on e.g https://discourse.jupyter.org/ for more insights: many of the folk that build and maintain the jupyter stack.
