### ISSUE TITLE
Package Notebook 7 pre-releases

### ISSUE THREAD

**Issue by jtpio** [conda-forge/notebook-feedstock#109]
Notebook 7 pre-releases have been released on PyPI for more than a year now:

- https://github.com/jupyter/notebook/releases/tag/v7.0.0a17
- https://pypi.org/project/notebook/#history

It would be great to also make them available on conda-forge.

For reference the JupyterLab 4 pre-releases are available on conda: https://github.com/conda-forge/jupyterlab-feedstock/tree/alpha-4.x

**Comment by bollwyvl** [comment]
Appears to work:

- [gist](https://gist.github.com/bollwyvl/3c5d37a4061189f434e0008976b8e9e2)
- [binder](https://gke2.mybinder.org/v2/git/https%3A%2F%2Fgist.github.com%2Fbollwyvl%2F3c5d37a4061189f434e0008976b8e9e2/HEAD)

**Comment by jtpio** [comment]
Oh wow, thanks for this!
