### ISSUE TITLE
Add top-level pin for `traitlets <5.10` for `notebook <6.5.6`

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/notebook-feedstock#132]
### Comment:

This will be a conda-forge-pinning change to address historical installs of:

https://github.com/jupyter/notebook/issues/7048

**Comment by minrk** [comment]
This would go in https://github.com/conda-forge/conda-forge-pinning-feedstock

**Comment by bollwyvl** [comment]
Yep, luckily i didn't confuse myself. And it got merged, so we can close this out.

**Comment by bollwyvl** [comment]
Of course, I'd _love_ to go back and make a `!=5.10.*` if we could resolve the `warn(stacklevel)` thing... unless more things are broken.
