### ISSUE TITLE
After upgrade to 6.2.0 notebooks cannot be opened.

### ISSUE THREAD

**Issue by jochym** [conda-forge/notebook-feedstock#83]
- [ ] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by blink1073** [comment]
My guess is that you're running into this: https://github.com/jupyter/nbformat/issues/206

**Comment by bollwyvl** [comment]
We've gotten the bad `nbformat 5.1.0` marked as `broken` so it should no longer be causing issues. Please re-open if something persists.

https://github.com/conda-forge/admin-requests/pull/216

**Comment by jochym** [comment]
Thanks
