### ISSUE TITLE
Jupiter Notebook not working under M1 mac OS 11.1

### ISSUE THREAD

**Issue by Johannes-Lange** [conda-forge/notebook-feedstock#85]
After ˋconda install notebook´ into my conda environment and starting it once, the whole environment is broken.
When running python from the terminal, I get the message ˋzsh: killed´, my IDE shows ˋprocess was killed by SIGKILL (Signal 9)´.
Uninstall the package doesn't fix this, I tried to create a new environment, this also doesn't work due to ˋzsh: killed´.

**Comment by bollwyvl** [comment]
The full output of `conda list --explicit` and `conda info --json`, redacted, if there's any sensitive paths, etc. would be very helpful, if it is capable of running those.

That being said: much like the architecture itself, conda-forge's M1 support is still very new, and cross-compiled to boot... there are some related things (e.g. https://github.com/conda-forge/ipython-feedstock/pull/129) which may be related, but we're kinda throwing darts here.

**Comment by erykoff** [comment]
It is possible that this is related to the above bug, but I know that I have successfully run jupyter notebooks when we did the port.  I will see if I can replicate.

**Comment by erykoff** [comment]
@Johannes-Lange I'll need more info.  Just now I was able to successfully make a new notebook env on both python 3.8 and 3.9 and everything worked as expected.
This `zsh: killed` is usually a sign of a code signing error.  As far as I know these have all been ironed out, but there's always the possibility that something went wrong on installation and corrupted a file.

**Comment by bollwyvl** [comment]
Oooh, if you downloaded miniforge/mambaforge through your browser, that could trigger it, no? Grabbing it with `curl` might work better.

**Comment by erykoff** [comment]
Ah, that shouldn't be an issue.  The binaries that are downloaded are signed (as well as the binaries and libraries built and distributed).  However, when things are installed the rpaths all have to be changed for the local installation, and this modification requires a re-signing of everything on install.  

Anyway, for this particular problem I think I need to know the exact list of packages in the environment.

**Comment by Johannes-Lange** [comment]
Unfortunately I hadn't much time to get all these. This occurred on two M1s, both with miniforge and an conda environment (only numpy, Pandas, pytorch and jupyter). On one Computer Jupyter has been working for weeks but yesterday (I think after MacOS 11.1 update) this error occurred after starting jupyter notebook. I then installed notebook on the other M1 to check if it's reproduceable and after starting it gave me the same zsh message.

**Comment by erykoff** [comment]
I don't believe pytorch has been ported to osx-arm64 yet, at least on the main channels.  Are you using the experimental one from `-c isuruf/label/pytorch` or are you running x86 under rosetta?

**Comment by Johannes-Lange** [comment]
I built it myself from the main branch. But this wasn’t the problem since the other M1 hasn’t  installed it. 

Von meinem iPhone gesendet

**Comment by erykoff** [comment]
Thanks.  So far I'm unable to replicate.  What version of conda are you using?

**Comment by erykoff** [comment]
Also, the new build of ipython is available, if for any reason that was related.

**Comment by Johannes-Lange** [comment]
miniforge3-4.9.2-4
and then the packages all installed directly into one environment, not the base.

**Comment by erykoff** [comment]
I just did `conda create -n nbtest5 python=3.9 pandas notebook numpy` and was able to start ipython, python, `jupyter notebook`, etc, and successfully import `numpy` and `pandas`, quit the notebook, and start both python and ipython.  I'm not sure what to look at now, but let me know if I'm missing something.

**Comment by jakirkham** [comment]
Johannes, maybe it would help if you could share a reproducer? Admittedly this may be hard to generate, but it would make debugging much more straightforward

**Comment by bollwyvl** [comment]
All builds from https://github.com/conda-forge/ipython-feedstock/pull/130 are up. Please test!

**Comment by bollwyvl** [comment]
Please re-open if additional issues occur.
