### ISSUE TITLE
How to get the recipe used to build notebook==6.0.3?

### ISSUE THREAD

**Issue by rahul26goyal** [conda-forge/notebook-feedstock#96]
- [ ] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

**Issue:**
Hi team 
I am new to the whole conda packaging framework..so please help me out here. 
I am trying to build a conda package on top on notebook==6.0.3 version with some patch. 
how to do get the `meta.yaml` file that was used to build the original package?

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by davidbrochart** [comment]
Hi @rahul26goyal, here is the `meta,yaml` for v6.0.3:
https://github.com/regro-cf-autotick-bot/notebook-feedstock/blob/c6655d75594d9c35e4884bcb1959c3be054cabe4/recipe/meta.yaml

**Comment by bollwyvl** [comment]
Fun fact: every `conda` package built by `conda-forge` (can't speak for other channels) contains the recipe it was built from, in both the "human" form as well as the rendered form. So you could crack open your local cache of that package (or grab it from [CDN](https://anaconda.org/conda-forge/notebook/files?version=6.0.3)). Inside the tarball, it's under `info/recipe/meta.yaml`. As `notebook` is _actually_ a pure-python package (even though it wasn't `noarch` at the time) it's probably not _that_ important which c compiler was around, but in general, it can be very useful for doing forensic builds, even if it falls a bit short of reproducible ones.

**Comment by rahul26goyal** [comment]
thanks a lot @davidbrochart  and @bollwyvl  for your response.
